# Generated by Django 4.2.7 on 2023-11-26 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('nif', models.CharField(max_length=9)),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(blank=True, max_length=10)),
                ('complement', models.CharField(blank=True, max_length=30)),
                ('neighborhood', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=100)),
                ('site_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
